name: Build site with pelican and upload to remote server

on:
  push:
    branches:
      - main
    paths:
      - 'content/**'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r action_requirements.txt

      - name: Build static site with Pelican
        run: |
          pelican content -s publishconf.py -o output
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} -H "${{ secrets.SERVER_ADDRESS }}" >> ~/.ssh/known_hosts
      
      - name: Upload site
        env:
          SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          TARGET_DIRECTORY: ${{ secrets.TARGET_DIRECTORY }}
        run: |
          rsync -e "ssh -p $SERVER_PORT" -avz --delete output/ $SERVER_USERNAME@$SERVER_ADDRESS:$TARGET_DIRECTORY
